# Generated by Django 5.2 on 2026-09-04.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("courses", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="curriculum_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Optional curriculum-context.v1 selection exported by Curriculum Expert. "
                    "SafeGloss stores the selection, not a copy of the provider taxonomy."
                ),
            ),
        ),
    ]
